/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Procceses.MessageSender;
import Procceses.Verification;
import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    MessageSender messageSender;
    String archivos = "", correos = "";

    public MainFrame() {
        initComponents();
        messageSender = new MessageSender();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPara = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelEnviar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelSalir = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanelDestinatarios = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelCC = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelCCO = new javax.swing.JPanel();
        jLabelCCO = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCuerpo = new javax.swing.JTextArea();
        jTextFieldCC = new javax.swing.JTextField();
        jTextFieldCCO = new javax.swing.JTextField();
        jPanelAdjunto = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAsunto = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabelCorreos = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelArchivos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 62, 70));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\migue\\OneDrive\\Documentos\\Archivos Universidad\\4to Semestre\\Topicos Avanzados de Progra\\1er Proyecto\\Archivos\\JavaMail Express Logo 1 mini.png")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 120));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Información del correo");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Para:");

        jTextFieldPara.setBackground(new java.awt.Color(57, 62, 70));
        jTextFieldPara.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldPara.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldPara.setText("Inserte el correo electronico");
        jTextFieldPara.setBorder(null);
        jTextFieldPara.setOpaque(false);
        jTextFieldPara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldParaMouseClicked(evt);
            }
        });
        jTextFieldPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldParaActionPerformed(evt);
            }
        });

        jPanelEnviar.setBackground(new java.awt.Color(97, 106, 119));
        jPanelEnviar.setForeground(new java.awt.Color(0, 0, 153));
        jPanelEnviar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanelEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelEnviarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEnviarMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enviar");

        javax.swing.GroupLayout jPanelEnviarLayout = new javax.swing.GroupLayout(jPanelEnviar);
        jPanelEnviar.setLayout(jPanelEnviarLayout);
        jPanelEnviarLayout.setHorizontalGroup(
            jPanelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnviarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanelEnviarLayout.setVerticalGroup(
            jPanelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnviarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSalir.setBackground(new java.awt.Color(97, 106, 119));
        jPanelSalir.setForeground(new java.awt.Color(0, 0, 153));
        jPanelSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Salir");

        javax.swing.GroupLayout jPanelSalirLayout = new javax.swing.GroupLayout(jPanelSalir);
        jPanelSalir.setLayout(jPanelSalirLayout);
        jPanelSalirLayout.setHorizontalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalirLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelSalirLayout.setVerticalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CC:");

        jPanelDestinatarios.setBackground(new java.awt.Color(97, 106, 119));
        jPanelDestinatarios.setForeground(new java.awt.Color(0, 0, 153));
        jPanelDestinatarios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanelDestinatarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDestinatariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDestinatariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDestinatariosMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Añadir destinatario");

        javax.swing.GroupLayout jPanelDestinatariosLayout = new javax.swing.GroupLayout(jPanelDestinatarios);
        jPanelDestinatarios.setLayout(jPanelDestinatariosLayout);
        jPanelDestinatariosLayout.setHorizontalGroup(
            jPanelDestinatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDestinatariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(45, 45, 45))
        );
        jPanelDestinatariosLayout.setVerticalGroup(
            jPanelDestinatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDestinatariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCC.setBackground(new java.awt.Color(97, 106, 119));
        jPanelCC.setForeground(new java.awt.Color(0, 0, 153));
        jPanelCC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanelCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCCMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Añadir CC");

        javax.swing.GroupLayout jPanelCCLayout = new javax.swing.GroupLayout(jPanelCC);
        jPanelCC.setLayout(jPanelCCLayout);
        jPanelCCLayout.setHorizontalGroup(
            jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(45, 45, 45))
        );
        jPanelCCLayout.setVerticalGroup(
            jPanelCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CCO:");

        jPanelCCO.setBackground(new java.awt.Color(97, 106, 119));
        jPanelCCO.setForeground(new java.awt.Color(0, 0, 153));
        jPanelCCO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanelCCO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCCOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCCOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCCOMouseExited(evt);
            }
        });

        jLabelCCO.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelCCO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCCO.setText("Añadir CCO");

        javax.swing.GroupLayout jPanelCCOLayout = new javax.swing.GroupLayout(jPanelCCO);
        jPanelCCO.setLayout(jPanelCCOLayout);
        jPanelCCOLayout.setHorizontalGroup(
            jPanelCCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCCOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCCO)
                .addGap(45, 45, 45))
        );
        jPanelCCOLayout.setVerticalGroup(
            jPanelCCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCCOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCCO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cuerpo del correo:");

        jTextAreaCuerpo.setBackground(new java.awt.Color(57, 62, 70));
        jTextAreaCuerpo.setColumns(20);
        jTextAreaCuerpo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextAreaCuerpo.setForeground(new java.awt.Color(240, 240, 240));
        jTextAreaCuerpo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCuerpo);

        jTextFieldCC.setBackground(new java.awt.Color(57, 62, 70));
        jTextFieldCC.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldCC.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCC.setText("Inserte el correo electronico");
        jTextFieldCC.setBorder(null);
        jTextFieldCC.setOpaque(false);
        jTextFieldCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCCMouseClicked(evt);
            }
        });

        jTextFieldCCO.setBackground(new java.awt.Color(57, 62, 70));
        jTextFieldCCO.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldCCO.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCCO.setText("Inserte el correo electronico");
        jTextFieldCCO.setBorder(null);
        jTextFieldCCO.setOpaque(false);
        jTextFieldCCO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCCOMouseClicked(evt);
            }
        });

        jPanelAdjunto.setBackground(new java.awt.Color(97, 106, 119));
        jPanelAdjunto.setForeground(new java.awt.Color(0, 0, 153));
        jPanelAdjunto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanelAdjunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAdjuntoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAdjuntoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAdjuntoMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Añadir archivo adjunto");

        javax.swing.GroupLayout jPanelAdjuntoLayout = new javax.swing.GroupLayout(jPanelAdjunto);
        jPanelAdjunto.setLayout(jPanelAdjuntoLayout);
        jPanelAdjuntoLayout.setHorizontalGroup(
            jPanelAdjuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdjuntoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        jPanelAdjuntoLayout.setVerticalGroup(
            jPanelAdjuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdjuntoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Asunto");

        jTextFieldAsunto.setBackground(new java.awt.Color(57, 62, 70));
        jTextFieldAsunto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldAsunto.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldAsunto.setText("Asunto");
        jTextFieldAsunto.setBorder(null);
        jTextFieldAsunto.setOpaque(false);
        jTextFieldAsunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldAsuntoMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Con los archivos:");

        jLabelCorreos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCorreos.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Se enviará a:");

        jLabelArchivos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelArchivos.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPara, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(jPanelCC, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(jPanelCCO, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanelAdjunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jPanelEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(401, 401, 401))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel17)
                    .addContainerGap(986, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPara, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addComponent(jPanelCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldCCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanelCCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelAdjunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabelCorreos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(586, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(164, 164, 164)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseExited
        // TODO add your handling code here:
        jPanelSalir.setBackground(new Color(97,106,119));
    }//GEN-LAST:event_jPanelSalirMouseExited

    private void jPanelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseEntered
        // TODO add your handling code here:
        jPanelSalir.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanelSalirMouseEntered

    private void jPanelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanelSalirMouseClicked

    private void jPanelEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEnviarMouseExited
        // TODO add your handling code here:
        jPanelEnviar.setBackground(new Color(97,106,119));
    }//GEN-LAST:event_jPanelEnviarMouseExited

    private void jPanelEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEnviarMouseEntered
        // TODO add your handling code here:
        jPanelEnviar.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanelEnviarMouseEntered

    private void jPanelEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEnviarMouseClicked
        // TODO add your handling code here:
        messageSender.setAsunto(jTextFieldAsunto.getText());
        messageSender.setMensajePrincipal(jTextAreaCuerpo.getText());
        
        messageSender.enviarMensaje();
    }//GEN-LAST:event_jPanelEnviarMouseClicked

    private void jTextFieldParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldParaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParaActionPerformed

    private void jTextFieldParaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldParaMouseClicked
        // TODO add your handling code here:
        jTextFieldPara.setText("");
    }//GEN-LAST:event_jTextFieldParaMouseClicked

    private void jPanelDestinatariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDestinatariosMouseClicked
        // TODO add your handling code here
        String correo = jTextFieldPara.getText();
        if(Verification.isEmailValid(correo)){
            messageSender.addPara(correo);
            correos = correos + correo + "\n";
            jLabelCorreos.setText(correos);

        }
    }//GEN-LAST:event_jPanelDestinatariosMouseClicked

    private void jPanelDestinatariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDestinatariosMouseEntered
        // TODO add your handling code here:
        jPanelDestinatarios.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanelDestinatariosMouseEntered

    private void jPanelDestinatariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDestinatariosMouseExited
        // TODO add your handling code here:
        jPanelDestinatarios.setBackground(new Color(97,106,119));
    }//GEN-LAST:event_jPanelDestinatariosMouseExited

    private void jPanelCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCCMouseClicked
        // TODO add your handling code here:
        String correo = jTextFieldCC.getText();
        if(Verification.isEmailValid(correo)){
            messageSender.addCC(correo);
            correos = correos + correo + "\n";
            jLabelCorreos.setText(correos);

        }
       
    }//GEN-LAST:event_jPanelCCMouseClicked

    private void jPanelCCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCCMouseEntered
        // TODO add your handling code here:
        jPanelCC.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanelCCMouseEntered

    private void jPanelCCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCCMouseExited
        // TODO add your handling code here:
        jPanelCC.setBackground(new Color(97,106,119));

    }//GEN-LAST:event_jPanelCCMouseExited

    private void jPanelCCOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCCOMouseClicked
        // TODO add your handling code here:
        String correo = jTextFieldCCO.getText();
        if(Verification.isEmailValid(correo)){
            messageSender.addCCO(correo);
            correos = correos + correo + "\n";
            jLabelCorreos.setText(correos);

        }
    }//GEN-LAST:event_jPanelCCOMouseClicked

    private void jPanelCCOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCCOMouseEntered
        // TODO add your handling code here:
        jPanelCCO.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanelCCOMouseEntered

    private void jPanelCCOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCCOMouseExited
        // TODO add your handling code here:
        jPanelCCO.setBackground(new Color(97,106,119));
    }//GEN-LAST:event_jPanelCCOMouseExited

    private void jPanelAdjuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAdjuntoMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
            messageSender.addPathFiles(fileChooser.getSelectedFile());
            String seleccionado = fileChooser.getSelectedFile().getName();
            archivos = archivos + seleccionado + ", ";
            jLabelArchivos.setText(archivos);
        }
        else JOptionPane.showMessageDialog(this, "Archivo no valido");
    }//GEN-LAST:event_jPanelAdjuntoMouseClicked

    private void jPanelAdjuntoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAdjuntoMouseEntered
        // TODO add your handling code here:
        jPanelAdjunto.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanelAdjuntoMouseEntered

    private void jPanelAdjuntoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAdjuntoMouseExited
        // TODO add your handling code here:
        jPanelAdjunto.setBackground(new Color(97,106,119));
    }//GEN-LAST:event_jPanelAdjuntoMouseExited

    private void jTextFieldCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCCMouseClicked
        // TODO add your handling code here:
        jTextFieldCC.setText("");
    }//GEN-LAST:event_jTextFieldCCMouseClicked

    private void jTextFieldCCOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCCOMouseClicked
        // TODO add your handling code here:
        jTextFieldCCO.setText("");
    }//GEN-LAST:event_jTextFieldCCOMouseClicked

    private void jTextFieldAsuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAsuntoMouseClicked
        // TODO add your handling code here:
        jTextFieldAsunto.setText("");
    }//GEN-LAST:event_jTextFieldAsuntoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelArchivos;
    private javax.swing.JLabel jLabelCCO;
    private javax.swing.JLabel jLabelCorreos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAdjunto;
    private javax.swing.JPanel jPanelCC;
    private javax.swing.JPanel jPanelCCO;
    private javax.swing.JPanel jPanelDestinatarios;
    private javax.swing.JPanel jPanelEnviar;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextAreaCuerpo;
    private javax.swing.JTextField jTextFieldAsunto;
    private javax.swing.JTextField jTextFieldCC;
    private javax.swing.JTextField jTextFieldCCO;
    private javax.swing.JTextField jTextFieldPara;
    // End of variables declaration//GEN-END:variables
}
